# production setup

services:
  types:
    image: types
    build: ./types
  backend:
    build: ./backend
    depends_on:
      - types
    networks:
      - backend
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    depends_on:
      - types
    networks:
      - frontend
  stack:
    build: ./stack
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
networks:
  frontend:
  backend: