# production setup

version: "3.9"
services:
  types:
    image: types
    build: ./types
  backend:
    image: 127.0.0.1:5000/stack-example/backend
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    depends_on:
      - types
    networks:
      - backend
    environment:
      - NODE_ENV=production
  frontend:
    image: 127.0.0.1:5000/stack-example/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    depends_on:
      - types
    networks:
      - frontend
  proxy:
    image: 127.0.0.1:5000/stack-example/proxy
    build: ./proxy
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
networks:
  frontend:
  backend:
